In [1]:
!pip install mysql-connector-python pandas matplotlib seaborn

Requirement already satisfied: mysql-connector-python in c:\users\pvshi\anaconda3\lib\site-packages (9.6.0)
Requirement already satisfied: pandas in c:\users\pvshi\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: matplotlib in c:\users\pvshi\anaconda3\lib\site-packages (3.8.4)
Requirement already satisfied: seaborn in c:\users\pvshi\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pvshi\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pvshi\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pvshi\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pvshi\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\pvshi\anaconda3\lib\site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\pvshi\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\pvshi\anaconda3\lib\site-packages (from matplotlib) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\pvshi\anaconda3\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\pvshi\anaconda3\lib\site-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=8 in c:\users\pvshi\anaconda3\lib\site-packages (from matplotlib) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\pvshi\anaconda3\lib\site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: six>=1.5 in c:\users\pvshi\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import pandas as pd
import mysql.connector

# Create connection
conn = mysql.connector.connect(
    host="18.136.157.135",
    user="dm_team7",
    password="DM!$!Team!72@04!23&",
    database="project_customer_segmentation"
)

# Load data
query = "SELECT * FROM customer"
df = pd.read_sql(query, conn)

# Preview
df.head()

C:\Users\pvshi\AppData\Local\Temp\ipykernel_11472\1720634187.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I100008,C199951,Male,65,Clothing,5,1500.40,Cash,10-07-2022,Emaar Square Mall
1,I100014,C138893,Male,55,Cosmetics,5,203.30,Cash,18-06-2021,Viaport Outlet
2,I100015,C132779,Female,35,Clothing,2,600.16,Debit Card,04-03-2021,Mall of Istanbul
3,I100024,C244411,Female,67,Books,3,45.45,Credit Card,05-01-2023,Emaar Square Mall
4,I100027,C150002,Female,19,Technology,4,4200.00,Cash,18-05-2022,Mall of Istanbul

In [3]:
df.shape
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99457 entries, 0 to 99456
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_no      99457 non-null  object
 1   customer_id     99457 non-null  object
 2   gender          99457 non-null  object
 3   age             99457 non-null  int64
 4   category        99457 non-null  object
 5   quantity        99457 non-null  int64
 6   price           99457 non-null  float64
 7   payment_method  99457 non-null  object
 8   invoice_date    99457 non-null  object
 9   shopping_mall   99457 non-null  object
dtypes: float64(1), int64(2), object(7)
memory usage: 7.6+ MB

invoice_no        0
customer_id       0
gender            0
age               0
category          0
quantity          0
price             0
payment_method    0
invoice_date      0
shopping_mall     0
dtype: int64

In [4]:
df['revenue'] = df['price'] * df['quantity']

In [5]:
bins = [0, 18, 25, 35, 45, 60, 100]
labels = ['Teen', 'Young Adult', 'Adult', 'Mid-Age', 'Senior', 'Elder']

df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels)

In [6]:
df.head()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,revenue,age_group
0,I100008,C199951,Male,65,Clothing,5,1500.40,Cash,10-07-2022,Emaar Square Mall,7502.00,Elder
1,I100014,C138893,Male,55,Cosmetics,5,203.30,Cash,18-06-2021,Viaport Outlet,1016.50,Senior
2,I100015,C132779,Female,35,Clothing,2,600.16,Debit Card,04-03-2021,Mall of Istanbul,1200.32,Adult
3,I100024,C244411,Female,67,Books,3,45.45,Credit Card,05-01-2023,Emaar Square Mall,136.35,Elder
4,I100027,C150002,Female,19,Technology,4,4200.00,Cash,18-05-2022,Mall of Istanbul,16800.00,Young Adult

In [7]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\pvshi\anaconda3\lib\site-packages (2.0.30)
Requirement already satisfied: pymysql in c:\users\pvshi\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\pvshi\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\pvshi\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)

In [8]:
from sqlalchemy import create_engine

# MySQL credentials
username = "dm_team7"
password = "DM!$!Team!72@04!23&"
host = "18.136.157.135"
port = "3306"
database = "project_customer_segmentation"

# Create connection
engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")